Repository masamichi2004/spino-cup, pull requests merged in 2024-09, with the labels that each got.

#11 feature: トレーニング画面のディレクトリUIの作成
  frontend/components.json
  frontend/components/ui/table.tsx
  frontend/package.json
  frontend/public/arrow.png
  frontend/public/copy.png
  frontend/src/app/home/[name]/[part]/[training]/page.tsx
  frontend/src/components/Accordion.tsx
  frontend/src/components/BackFile.tsx
  frontend/src/components/BackLink.tsx
  frontend/src/components/TrainingFile.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/feature/home/name/part/training/Training.tsx
  pnpm-lock.yaml
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#12 delete: Dockerコンテナを削除
  docker-compose.yml
  docker/backend.dockerfile
  docker/frontend.dockerfile
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#13 [FEAT]ユーザー画面の静的コンポーネント作成
  frontend/src/app/home/[name]/page.tsx
  frontend/src/components/HomeNameMain.tsx
  frontend/src/feature/home/name/Name.tsx
  pnpm-lock.yaml
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#10 feature: Github Auth認証を追加
  .env.examples
  backend/package.json
  backend/src/index.ts
  backend/src/middleware/github.auth.ts
  backend/src/repository/user.repo.ts
  backend/src/service/user.service.ts
  pnpm-lock.yaml
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#18 [FEAT] 個々のPRページのコンポーネント作成
  frontend/package.json
  frontend/public/smile.png
  frontend/src/app/home/[name]/[part]/pulls/[id]/page.tsx
  frontend/src/app/home/[name]/[part]/pulls/page.tsx
  frontend/src/components/PrMain.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/feature/home/name/part/pulls/id/PR.tsx
  frontend/tailwind.config.js
  pnpm-lock.yaml
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#15 update: Github AppsのOAuth認証に変更
  backend/package.json
  backend/src/index.ts
  backend/src/middleware/github.auth.ts
  backend/src/model/user.model.ts
  pnpm-lock.yaml
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#20 [FIX] ディレクトリ構成を変更
  frontend/src/app/home/[name]/[part]/[training]/page.tsx
  frontend/src/app/home/[name]/[part]/page.tsx
  frontend/src/app/home/[name]/[part]/pulls/[id]/page.tsx
  frontend/src/app/home/[name]/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/feature/Accordion/Accordion.tsx
  frontend/src/feature/BackFile/BackFile.tsx
  frontend/src/feature/BackLink/BackLink.tsx
  frontend/src/feature/Header/Header.tsx
  frontend/src/feature/HomeNameMain/HomeNameMain.tsx
  frontend/src/feature/HumberMenu/HumberMenu.tsx
  frontend/src/feature/PrMain/PrMain.tsx
  frontend/src/feature/RepositoryInfo/RepositoryInfo.tsx
  frontend/src/feature/RepositoryList/RepositoryList.tsx
  frontend/src/feature/TrainingFile/TrainingFile.tsx
  frontend/src/feature/home/Home.tsx
  frontend/src/feature/home/name/Name.tsx
  frontend/src/feature/home/name/part/Part.tsx
  frontend/src/feature/home/name/part/pulls/id/PR.tsx
  frontend/src/feature/home/name/part/training/Training.tsx
  frontend/src/feature/user/User.tsx
  frontend/tailwind.config.js
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#19 feature: UserをAuthorizeした後に追加する処理
  .env.examples
  backend/src/index.ts
  backend/src/lib/firestore.tool.ts
  backend/src/middleware/firebase.config.ts
  backend/src/middleware/github.auth.ts
  backend/src/model/repository.model.ts
  backend/src/model/user.model.ts
  backend/src/repository/repository.repo.ts
  backend/src/repository/user.repo.ts
  backend/src/service/user.service.ts
Labels: 💪むきむきレビュー待ち💪, ✌️2approve希望

#21 feature: モックのエンドポイントを追加
  backend/src/index.ts
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#23 [FIX] ヘッダーをログイン画面以外に適応
  frontend/src/app/home/[name]/layout.tsx
  frontend/src/app/layout.tsx
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#30 fix: ユーザー作成のユニーク制約を追加
  backend/src/lib/firestore.tool.ts
  backend/src/middleware/firebase.config.ts
  backend/src/model/repository.model.ts
  backend/src/model/user.model.ts
  backend/src/repository/pullRequest.repo.ts
  backend/src/repository/repository.repo.ts
  backend/src/repository/user.repo.ts
  backend/src/service/user.service.ts
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#29 feature: Github APIで既存リポジトリにディレクトリを追加するロジックの追加
  backend/src/github/repository/createRepository.ts
  backend/src/index.ts
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#33 ログインコンポーネントの作成
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/feature/Login/Login.tsx
  frontend/src/middleware.ts
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#32 fix: リポジトリ作成のエンドポイントをPOSTに修正
  backend/src/index.ts
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#34 feature: Github APIでコミットを実行するロジックを追加
  backend/src/github/repository/createRepository.ts
  backend/src/index.ts
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪, マッスル修正中😀

#35 feature: ユーザーを取得するエンドポイントと処理
  backend/src/github/repository/createRepository.ts
  backend/src/index.ts
  backend/src/repository/user.repo.ts
  backend/src/service/user.service.ts
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#37 [FIX]細かい修正
  frontend/public/macho.ico
  frontend/src/app/icon.ico
  frontend/src/app/layout.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/feature/Header/Header.tsx
  frontend/src/feature/HumberMenu/HumberMenu.tsx
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#39 [FEAT] /user/:userIdを叩いてできるだけ表示
  frontend/src/app/home/[name]/layout.tsx
  frontend/src/app/home/[name]/page.tsx
  frontend/src/feature/Header/Header.tsx
  frontend/src/feature/Header/fetchHeaderData.ts
  frontend/src/feature/Header/useHeaderMain.ts
  frontend/src/feature/HomeNameMain/HomeName.ts
  frontend/src/feature/HomeNameMain/HomeNameMain.tsx
  frontend/src/feature/HomeNameMain/useHomeName.ts
  frontend/src/feature/PrMain/PrMain.tsx
  frontend/src/feature/RepositoryList/RepositoryList.tsx
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#45 fix: CORSの設定を修正
  backend/src/middleware/cors.ts
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪

#51 add: loading component を追加しました
  frontend/public/meramera7-1.png
  frontend/src/app/loading.tsx
  frontend/src/feature/Header/Header.tsx
  frontend/src/feature/HomeNameMain/HomeNameMain.tsx
  frontend/src/feature/Loading/Loading.tsx
  frontend/src/feature/NewRepositoryButton/NewRepositoryButton.tsx
  frontend/src/feature/TrainingFile/TrainingFile.tsx
Labels: ✌️1approve希望, 💪むきむきレビュー待ち💪
